#!/bin/bash

if (( EUID != 0 ))
then
    exec sudo "$0" "$@"
fi

set -euo pipefail
shopt -s nullglob

LC_ALL="C"
LANG="C"
LANGUAGE="C"

DEBUG="${DEBUG:-false}"

VERSION=$1

KERNEL_DTB_PATH="/usr/lib/linux-image-${VERSION}/rockchip"

DTB_FILENAME="rk3566-quartz64-b.dtb"
DTB_ALIASNAME="rk3566-rock-3c-aic8800ds2.dtb"
DTB_FILE="${KERNEL_DTB_PATH}/${DTB_FILENAME}"
DTB_ALIAS="${KERNEL_DTB_PATH}/${DTB_ALIASNAME}"

! [ -f "${DTB_ALIAS}" ]; IS_FILE=$?
! [ -h "${DTB_ALIAS}" ]; IS_LINK=$?

if [ ${IS_FILE} -eq ${IS_LINK} ] ; then
    echo "Using ${DTB_FILENAME} as ${DTB_ALIASNAME} (hack)"
    ln -sf "${DTB_FILENAME}" "${DTB_ALIAS}"
else
    echo "Keeping ${DTB_ALIASNAME} as it is."
fi

cp -L "${DTB_ALIAS}" "/boot/dtb/rockchip/${DTB_ALIASNAME}"
